-- ========================================================================================
-- СКРИПТ НАСТРОЙКИ БАЗЫ ДАННЫХ UCMAGAZ
-- ========================================================================================
-- Этот файл содержит полную настройку базы данных с нуля.
-- Выполните его целиком в Supabase SQL Editor - база настроится автоматически.
--
-- Особенности:
-- - Безопасное удаление существующих таблиц (IF EXISTS + CASCADE)
-- - Безопасная вставка данных (ON CONFLICT DO NOTHING / DO UPDATE)
-- - Автоматическое добавление новых колонок Prime (если не существуют)
-- - Все политики доступа RLS включены
--
-- После выполнения скрипта база будет готова к работе!
-- ========================================================================================



-- Создание таблицы настроек с дополнительными колонками для PP и билетов
CREATE TABLE settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  usd_rate FLOAT8 DEFAULT 78.0,
  markup_rub_default FLOAT8 DEFAULT 260.0,
  fee_percent FLOAT8 DEFAULT 0.052,
  pp_price_usd FLOAT8 DEFAULT 0.1, -- Цена 10000 ПП в USD
  pp_markup_rub INTEGER DEFAULT 0, -- Маржа для ПП
  ticket_price_usd FLOAT8 DEFAULT 0.01, -- Цена 100 билетов в USD
  ticket_markup_rub INTEGER DEFAULT 0, -- Маржа для билетов
  prime_price_usd FLOAT8 DEFAULT 0.05, -- Цена Prime в USD
  prime_markup_rub INTEGER DEFAULT 0, -- Маржа для Prime
  prime_plus_price_usd FLOAT8 DEFAULT 0.08, -- Цена Prime Plus в USD
  prime_plus_markup_rub INTEGER DEFAULT 0, -- Маржа для Prime Plus
  CONSTRAINT single_row CHECK (id = 1)
);

-- Создание таблицы продуктов UC
CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  amount_uc INTEGER NOT NULL,
  price_usd FLOAT8 NOT NULL,
  markup_rub FLOAT8 DEFAULT 0,
  image_url TEXT,
  sort_order INTEGER DEFAULT 0
);

-- Создание таблицы склада кодов
CREATE TABLE codes_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  value INTEGER NOT NULL, -- Номинал UC
  is_used BOOLEAN DEFAULT false,
  status TEXT, -- Для RESERVED и т.д.
  used_at TIMESTAMP WITH TIME ZONE,
  buyer_uid TEXT,
  order_id BIGINT,
  error_log TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Создание таблицы заказов
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid_player TEXT NOT NULL,
  user_chat_id BIGINT,
  amount_uc INTEGER NOT NULL,
  price_rub FLOAT8 NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_id TEXT,
  final_amount FLOAT8,
  commission_amount FLOAT8,
  is_code_order BOOLEAN DEFAULT false, -- Для промокодов
  order_type TEXT DEFAULT 'uc', -- 'uc', 'pp', 'tickets'
  completed_at TIMESTAMP WITH TIME ZONE,
  details TEXT, -- JSON с отчетом
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Создание таблицы аккаунтов Midasbuy
CREATE TABLE midas_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  last_used_at TIMESTAMP WITH TIME ZONE
);

-- Создание таблицы для ПП (если нужно для будущего)
CREATE TABLE pp_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price_rub INTEGER NOT NULL,
  image_url TEXT DEFAULT '/pp-icon.png'
);

-- Создание таблицы базовых номиналов
CREATE TABLE base_denominations (
  id SERIAL PRIMARY KEY,
  amount_uc INTEGER NOT NULL UNIQUE,
  price_usd FLOAT8 NOT NULL
);

-- Создание таблицы для скинов
CREATE TABLE skins_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price_rub INTEGER NOT NULL,
  image_url TEXT
);

-- Включение RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE codes_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE midas_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE pp_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE base_denominations ENABLE ROW LEVEL SECURITY;
ALTER TABLE skins_products ENABLE ROW LEVEL SECURITY;

-- Политики доступа
CREATE POLICY "Enable all for settings" ON settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for codes_stock" ON codes_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for midas_accounts" ON midas_accounts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for pp_products" ON pp_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for base_denominations" ON base_denominations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for skins_products" ON skins_products FOR ALL USING (true) WITH CHECK (true);

-- Вставка настроек (безопасная)
INSERT INTO settings (id, usd_rate, markup_rub_default, fee_percent, pp_price_usd, pp_markup_rub, ticket_price_usd, ticket_markup_rub, prime_price_usd, prime_markup_rub, prime_plus_price_usd, prime_plus_markup_rub) 
VALUES (1, 78.0, 260.0, 0.052, 0.1, 0, 0.01, 0, 0.05, 0, 0.08, 0)
ON CONFLICT (id) DO UPDATE SET
  usd_rate = EXCLUDED.usd_rate,
  markup_rub_default = EXCLUDED.markup_rub_default,
  fee_percent = EXCLUDED.fee_percent,
  pp_price_usd = EXCLUDED.pp_price_usd,
  pp_markup_rub = EXCLUDED.pp_markup_rub,
  ticket_price_usd = EXCLUDED.ticket_price_usd,
  ticket_markup_rub = EXCLUDED.ticket_markup_rub,
  prime_price_usd = EXCLUDED.prime_price_usd,
  prime_markup_rub = EXCLUDED.prime_markup_rub,
  prime_plus_price_usd = EXCLUDED.prime_plus_price_usd,
  prime_plus_markup_rub = EXCLUDED.prime_plus_markup_rub;

-- Вставка продуктов UC (безопасная)
INSERT INTO products (amount_uc, price_usd, markup_rub, image_url, sort_order) VALUES
(60, 0.75, 15.0, '/uc-60.jpg', 1),
(120, 1.50, 25.0, '/uc-60.jpg', 2),
(180, 2.25, 40.0, '/uc-60.jpg', 3),
(240, 3.00, 50.0, '/uc-60.jpg', 4),
(325, 4.00, 50.0, '/uc-325.jpg', 5),
(385, 4.75, 60.0, '/uc-325.jpg', 6),
(445, 5.50, 70.0, '/uc-325.jpg', 7),
(660, 8.20, 90.0, '/uc-325.jpg', 8),
(720, 8.90, 100.0, '/uc-325.jpg', 9),
(985, 12.00, 150.0, '/uc-325.jpg', 10),
(1320, 16.00, 180.0, '/uc-325.jpg', 11),
(1797, 21.00, 200.0, '/uc-1800-5650.jpg', 12),
(1920, 23.00, 220.0, '/uc-1800-5650.jpg', 13),
(2125, 25.50, 240.0, '/uc-1800-5650.jpg', 14),
(2460, 29.50, 260.0, '/uc-1800-5650.jpg', 15),
(3850, 42.00, 300.0, '/uc-1800-5650.jpg', 16),
(4510, 50.50, 350.0, '/uc-1800-5650.jpg', 17),
(5650, 63.00, 400.0, '/uc-1800-5650.jpg', 18),
(8100, 88.00, 500.0, '/uc-8100.jpg', 19),
(9900, 110.00, 600.0, '/uc-8100.jpg', 20),
(11950, 133.00, 700.0, '/uc-8100.jpg', 21),
(16200, 180.00, 1000.0, '/uc-8100.jpg', 22),
(24300, 270.00, 1500.0, '/uc-8100.jpg', 23),
(32400, 360.00, 2000.0, '/uc-8100.jpg', 24),
(40500, 450.00, 2500.0, '/uc-8100.jpg', 25),
(81000, 900.00, 5000.0, '/uc-8100.jpg', 26)
ON CONFLICT DO NOTHING;

-- Вставка базовых номиналов
INSERT INTO base_denominations (amount_uc, price_usd) VALUES
(60, 0.75),
(325, 4.00),
(660, 8.20),
(1800, 21.00),
(3850, 42.00),
(8100, 88.00)
ON CONFLICT (amount_uc) DO UPDATE SET price_usd = EXCLUDED.price_usd;

-- Вставка аккаунтов Midasbuy
INSERT INTO midas_accounts (email, password, is_active) VALUES
('MidasBuyMy1@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy2@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy3@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy4@outlook.com', 'Nikitamidas123!', true),
('MidasBuyMy5@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy6@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy7@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy8@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy9@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy10@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy11@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy12@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy13@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy14@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy15@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy16@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy17@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy18@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy19@hotmail.com', 'Nikitamidas123!', true),
('MidasBuyMy20@hotmail.com', 'Nikitamidas123!', true)
ON CONFLICT (email) DO UPDATE SET password = EXCLUDED.password;

-- Безопасное добавление колонок Prime (если они не существуют)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'settings' AND column_name = 'prime_price_usd') THEN
        ALTER TABLE settings ADD COLUMN prime_price_usd FLOAT8 DEFAULT 0.05;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'settings' AND column_name = 'prime_markup_rub') THEN
        ALTER TABLE settings ADD COLUMN prime_markup_rub INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'settings' AND column_name = 'prime_plus_price_usd') THEN
        ALTER TABLE settings ADD COLUMN prime_plus_price_usd FLOAT8 DEFAULT 0.08;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'settings' AND column_name = 'prime_plus_markup_rub') THEN
        ALTER TABLE settings ADD COLUMN prime_plus_markup_rub INTEGER DEFAULT 0;
    END IF;
END $$;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_1m_rub INTEGER DEFAULT 150;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_3m_rub INTEGER DEFAULT 400;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_6m_rub INTEGER DEFAULT 750;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_12m_rub INTEGER DEFAULT 1400;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_1m_rub INTEGER DEFAULT 250;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_3m_rub INTEGER DEFAULT 700;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_6m_rub INTEGER DEFAULT 1300;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_12m_rub INTEGER DEFAULT 2400;


ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_price_usd FLOAT8 DEFAULT 0.05;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_markup_rub INTEGER DEFAULT 0;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_price_usd FLOAT8 DEFAULT 0.08;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS prime_plus_markup_rub INTEGER DEFAULT 0;