CREATE TABLE IF NOT EXISTS broadcast_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    username VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE(chat_id)
);

CREATE INDEX IF NOT EXISTS idx_broadcast_users_chat_id ON broadcast_users(chat_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_users_active ON broadcast_users(is_active);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_broadcast_users_updated_at 
    BEFORE UPDATE ON broadcast_users 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
